### ISSUE TITLE
Warrior gets stuck with a lot of {"data":"400 items queued for deduplication","status_code":200} lines

### ISSUE THREAD

**Issue by kotenok2000** [ArchiveTeam/telegram-grab#3]
Item post:samanebartar:108002post:dentalmark:4940post:ofoqna:4169channel:HuobiGlobal_zwpost:Accounting_House:9887post:LKMRTG:34post:aarjam:128628post:diecast_arena:3637post:linkdonycom:59698post:VaagdeviInfo:198post:BigHodL:5907post:kamyarchanell:975post:thjbk:5944post:sorkhabysport:121post:Beshno_az_Neyy:2840post:khabarenergy:3207post:itarabar:73060post:Xbox_St:3300post:elenadreamhouse1:17022post:HyperClash:50936

**Comment by Arkiver2** [comment]
Not a big. This is caused by item `channel:HuobiGlobal_zw` for which more than 800000 posts are discovered. These posts are queued back to the tracker, leading to at least 2000 `{"data":"400 items queued for deduplication","status_code":200}` lines, making it seem like the items it 'stuck'.

However, some information on progress should be added here.

**Comment by Arkiver2** [comment]
Showing progress now with c98c5e14c4e52991ba9897794a28830fbbe05516.
